: script-binding select/menu

g ignore
g-p script-binding select/select-playlist
g-s script-binding select/select-sid
g-S script-binding select/select-secondary-sid
g-a script-binding select/select-aid
g-v script-binding select/select-vid
g-t script-binding select/select-track
g-c script-binding select/select-chapter
g-e script-binding select/select-edition
g-l script-binding select/select-subtitle-line
g-d script-binding select/select-audio-device
g-h script-binding select/select-watch-history
g-w script-binding select/select-watch-later
g-b script-binding select/select-binding
g-r script-binding select/show-properties
g-m script-binding select/menu
g-? script-binding stats/display-page-4-toggle

HOME seek 0 absolute       # seek to the start
h seek -5                  # seek 5 seconds backward
l seek  5                  # seek 5 seconds forward
L seek  60                 # seek 1 minute forward
H seek -60                 # seek 1 minute backward
Ctrl+h frame-back-step     # seek 1 frame backward
Ctrl+l frame-step          # seek 1 frame forward

> playlist-next            # skip to the next file
< playlist-prev            # skip to the previous file

UP         add volume 1
Shift+UP   add volume 10
DOWN       add volume -1
Shift+DOWN add volume -10

= set speed 1.0            # reset the speed to normal
+ add speed 0.25           # decrease the playback speed
- add speed -0.25          # increase the playback speed
* multiply speed 2.0       # double the playback speed
_ multiply speed 0.5       # halve the playback speed

Alt+0 set video-zoom 0; no-osd set panscan 0; no-osd set video-pan-x 0; no-osd set video-pan-y 0; no-osd set video-align-x 0; no-osd set video-align-y 0 # reset zoom and pan settings

Alt+h add video-pan-x 0.1        # move the video right
Alt+l add video-pan-x -0.1       # move the video left
Alt+k add video-pan-y 0.1        # move the video down
Alt+j add video-pan-y -0.1       # move the video up
Alt++ add video-zoom  0.1        # zoom in
Alt+- add video-zoom  -0.1       # zoom out

Ctrl+Alt+h add video-pan-x 0.01  # move the video right
Ctrl+Alt+l add video-pan-x -0.01 # move the video left
Ctrl+Alt+k add video-pan-y 0.01  # move the video down
Ctrl+Alt+j add video-pan-y -0.01 # move the video up
Ctrl+Alt++ add video-zoom  0.01  # zoom in
Ctrl+Alt+- add video-zoom  -0.01 # zoom out

Alt+H add video-pan-x 0.5        # move the video right
Alt+L add video-pan-x -0.5       # move the video left
Alt+K add video-pan-y 0.5        # move the video down
Alt+J add video-pan-y -0.5       # move the video up
Alt+* add video-zoom  0.5        # zoom in
Alt+_ add video-zoom  -0.5       # zoom out

Ctrl+Shift+h cycle-values hwdec no auto
