#!/bin/bash

DIR=$(dirname $(realpath $0))

WINDOW_ID_CONKY=/tmp/conky_window_id
WINDOW_ID_TOP=/tmp/polybar_top_window_id
WINDOW_ID_EXPANDED=/tmp/polybar_expanded_window_id

conky_launch() {
    # Hacky X11 magic to make Conky appear above polybar
    killall conky
    # xdotool search can't find Conky's window but fortunately Conky outputs it
    conky -c ~/.config/conky/config 2> /tmp/conky_out
    # Extract the hex window id from Conky's output
    HEX=$(awk '/drawing to created window/ {print $NF}' /tmp/conky_out | tr -d '()' | awk -Fx '{print $2}')
    WIN_ID=$(( 16#$HEX )) # convert to decimal
    xdotool windowunmap $WIN_ID
    echo $WIN_ID > $WINDOW_ID_CONKY
}

polybar_launch() {
    killall polybar
    echo launchPolybar
    polybar top &
    xdotool search --sync --pid $! > $WINDOW_ID_TOP

    polybar expanded &
    xdotool search --sync --pid $! > $WINDOW_ID_EXPANDED

    bar_collapse
}

launch() {
    #conky_launch
    #sleep 1
    polybar_launch
}

bar_expand() {
    xdotool windowmap $(cat $WINDOW_ID_EXPANDED)
}

bar_collapse() {
    xdotool windowunmap $(cat $WINDOW_ID_EXPANDED)
}

options_open() {
    bar_expand    
    echo "open" > /tmp/polybar_side_panel_state
    #ID_CONKY=$(cat $WINDOW_ID_CONKY)
    #xdotool windowmap $ID_CONKY
    #xdotool windowraise $ID_CONKY
}

options_close() {    
    #echo "open" > /tmp/polybar_side_panel_state
    #ID_CONKY=$(cat $WINDOW_ID_CONKY)
    #xdotool windowunmap $ID_CONKY
    bar_collapse
}

case "$1" in
    open_options)
        options_open;;
    close_options)
        options_close;;
    launch)
        launch;;
esac


